__version__: str

from typing import Any, Iterable, Optional, Sequence

class WeightedGSSSummary:
    top_values_count: int
    upperbranch_nodes: int
    interface_nodes: int
    lower_nodes: int
    lower_general_nodes: int
    lower_segment_nodes: int
    total_unique_nodes: int
    total_edges: int
    weight_instances: int
    max_depth: int

class WeightedGSS:
    def __init__(self) -> None: ...
    @classmethod
    def empty(cls) -> WeightedGSS: ...
    @classmethod
    def from_stacks(cls, stacks: Iterable[tuple[Sequence[Any], Any]]) -> WeightedGSS: ...
    @classmethod
    def from_unweighted(cls, stacks: Iterable[Sequence[Any]]) -> WeightedGSS: ...
    @classmethod
    def from_single_stack(cls, stack: Sequence[Any], weight: Any = None) -> WeightedGSS: ...
    @classmethod
    def merge_many(cls, gsses: Iterable[WeightedGSS]) -> WeightedGSS: ...
    def to_stacks(self, max_stacks: int = 4096) -> list[tuple[list[Any], Any]]: ...
    def push(self, value: Any) -> WeightedGSS: ...
    def pop(self) -> WeightedGSS: ...
    def popn(self, count: int) -> WeightedGSS: ...
    def isolate(self, value: Optional[Any]) -> WeightedGSS: ...
    def merge(self, other: WeightedGSS) -> WeightedGSS: ...
    def fuse(self, levels: Optional[int] = None) -> WeightedGSS: ...
    def peek(self) -> set[Any]: ...
    def join_weights(self) -> Optional[Any]: ...
    def is_empty(self) -> bool: ...
    def max_depth(self) -> int: ...
    def path_count_at_most(self, limit: int) -> int: ...
    def summary(self) -> WeightedGSSSummary: ...
