from typing import Any, Iterable, List, Sequence, Set, Tuple

__version__: str

class WeightedGSS:
    def __init__(self) -> None: ...

    @classmethod
    def from_stack(
        cls, stack: Sequence[Any], weight: Any = None
    ) -> "WeightedGSS": ...

    @classmethod
    def from_stacks(
        cls, entries: Iterable[Tuple[Sequence[Any], Any]]
    ) -> "WeightedGSS": ...

    @classmethod
    def from_unweighted(
        cls, stacks: Iterable[Sequence[Any]]
    ) -> "WeightedGSS": ...

    @classmethod
    def merge_all(cls, values: Iterable["WeightedGSS"]) -> "WeightedGSS": ...

    def with_stack(
        self, stack: Sequence[Any], weight: Any = None
    ) -> "WeightedGSS": ...
    def merge(self, other: "WeightedGSS") -> "WeightedGSS": ...
    def push(self, value: Any) -> "WeightedGSS": ...
    def pop(self) -> "WeightedGSS": ...
    def pop_n(self, count: int) -> "WeightedGSS": ...
    def top(self) -> Any: ...
    def tops(self) -> Set[Any]: ...
    def has_empty_stack(self) -> bool: ...
    def retain_top(self, value: Any) -> "WeightedGSS": ...
    def retain_empty(self) -> "WeightedGSS": ...
    def pop_top(self, value: Any) -> "WeightedGSS": ...
    def pop_branches(self) -> List[Tuple[Any, "WeightedGSS"]]: ...
    def joined_weight(self) -> Any: ...
    def empty_weight(self) -> Any: ...
    def to_stacks(
        self, max_paths: int = 4096
    ) -> List[Tuple[List[Any], Any]]: ...
    def is_empty(self) -> bool: ...
    def max_depth(self) -> int: ...
    def __bool__(self) -> bool: ...
