from typing import Any, Iterable, Optional, Sequence

class LeveledGSSSummary:
    top_values_count: int
    upperbranch_nodes: int
    interface_nodes: int
    lower_nodes: int
    lower_general_nodes: int
    lower_segment_nodes: int
    total_unique_nodes: int
    total_edges: int
    accumulator_instances: int
    max_depth: int

class LeveledGSS:
    def __init__(self) -> None: ...
    @classmethod
    def empty(cls) -> LeveledGSS: ...
    @classmethod
    def from_stacks(cls, stacks: Iterable[tuple[Sequence[Any], Any]]) -> LeveledGSS: ...
    @classmethod
    def from_unweighted(cls, stacks: Iterable[Sequence[Any]]) -> LeveledGSS: ...
    @classmethod
    def from_single_stack(cls, stack: Sequence[Any], accumulator: Any = None) -> LeveledGSS: ...
    @classmethod
    def merge_many(cls, gsses: Iterable[LeveledGSS]) -> LeveledGSS: ...
    def to_stacks(self, max_stacks: int = 4096) -> list[tuple[list[Any], Any]]: ...
    def push(self, value: Any) -> LeveledGSS: ...
    def pop(self) -> LeveledGSS: ...
    def popn(self, count: int) -> LeveledGSS: ...
    def isolate(self, value: Optional[Any]) -> LeveledGSS: ...
    def merge(self, other: LeveledGSS) -> LeveledGSS: ...
    def fuse(self, levels: Optional[int] = None) -> LeveledGSS: ...
    def peek(self) -> set[Any]: ...
    def reduce_acc(self) -> Optional[Any]: ...
    def is_empty(self) -> bool: ...
    def max_depth(self) -> int: ...
    def path_count_at_most(self, limit: int) -> int: ...
    def summary(self) -> LeveledGSSSummary: ...
